export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const DELETE_USERS_REQUEST = 'DELETE_USERS_REQUEST'
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS'
export const DELETE_USERS_FAILURE = 'DELETE_USERS_FAILURE'

export const ADD_USER = 'ADD_USER'

export const GETALL_TODO_REQUEST = 'GETALL_TODO_REQUEST'
export const GETALL_TODO_SUCCESS = 'GETALL_TODO_SUCCESS'
export const GETALL_TODO_FAILURE = 'GETALL_TODO_FAILURE'

export const GETALL_ALBUM_REQUEST = 'GETALL_ALBUM_REQUEST'
export const GETALL_ALBUM_SUCCESS = 'GETALL_ALBUM_SUCCESS'
export const GETALL_ALBUM_FAILURE = 'GETALL_ALBUM_FAILURE'

export const GETALL_POST_REQUEST = 'GETALL_POST_REQUEST'
export const GETALL_POST_SUCCESS = 'GETALL_POST_SUCCESS'
export const GETALL_POST_FAILURE = 'GETALL_POST_FAILURE'

export const GETALL_COMMENT_REQUEST = 'GETALL_COMMENT_REQUEST'
export const GETALL_COMMENT_SUCCESS = 'GETALL_COMMENT_SUCCESS'
export const GETALL_COMMENT_FAILURE = 'GETALL_COMMENT_FAILURE'